### ISSUE TITLE
kbfsfuse using a lot of memory

### ISSUE THREAD

**Issue by heyitswither** [keybase/kbfs#1246] opened 2017-10-08 19:42 UTC
![](https://plz-notice.me/2JihSnAs.png)

This is running on Ubuntu 16.04 with keybase version 1.0.34-20171006165932+d0664a9cb.

**Comment by strib** [comment] 2017-10-08 19:56
Hi @heyitswither, would you be willing to give more absolute numbers, rather than just percents?  We try to size memory usage based on your available memory, but it's hard to know here if we're doing that correctly.

Also, can you do a `keybase log send`, and report the resulting ID here, so we can have more info?  Thanks!

**Comment by heyitswither** [comment] 2017-10-08 20:20
Well I don't know what I did, but it's working fine now. will report if it happens again.

**Comment by ObscureScience** [comment] 2017-12-05 11:08
Was unsure if my `keybase send log` registered my feedback, as I got another feedback prompt after hitting enter. However: kbfsfuse process is using lots of memory. This occured after deleting a rather l
arge ~4GB file from keybase causing OOM and even killing a few processes. System
 has 6BG ram, and a zswap "partition" of around 1.2GB. I hope it's ok that I reuse this issue. The actual log id of my log send: 48559d3179f5fb27659e3c1c

**Comment by strib** [comment] 2017-12-05 18:25
Hi @ObscureScience, can you please elaborate on what you mean by "lots of memory" and "causing OOM"?  I don't see any KBFS crashes in your logs, so I'm not sure what OOM you are seeing.  KBFS keeps an in-memory cache of recently-read data, but it should be capped at a max amount based on the memory of your device.  I would expect the kbfsfuse process to max out somewhere around 1-1.5GB if it's being heavily used.  If you're seeing us use much more than that, there probably is a bug.

**Comment by ObscureScience** [comment] 2017-12-05 21:19
Ofcourse. I'm not entirely sure how to interpret htop memory numbersm but virtual memory usage was my entire memory, and RES (resident?) was around 3.2GB. The system phased in and out of being responsive (until not even updating screen) and when I got some control again I had lost a terminal with only a shell running. I left the computer for about 30mins and it responded when I came back, but became unresponsive again to the point of no return so I had to hard reset. kbfsfuse was always on top in memory usage, but only using around 10% cpu for the whole time. It was around one hour between I deleted the file from keybase and I had to restart.

**Comment by strib** [comment] 2017-12-05 21:26
Thanks!  RES is the important number here, the virtual memory is known to be high because the programming language we use (Go) doesn't release that back unless it has to (but it shouldn't indicate anything harmful).

But a RES that big is unexpected and bad, and might indicate a memory leak of some kind.  I will look more carefully at the log.  Was it an "iso.part" file that you deleted?

**Comment by ObscureScience** [comment] 2017-12-05 21:29
That is almost what the file was. It was a completed iso of Qubes OS downloaded as a torrent directly to keybase. I guess that's not an appropriate usage.

**Comment by strib** [comment] 2017-12-05 21:30
Nothing wrong with doing that.  I do see something fishy in the logs around that file being deleted, so I'll keep investigating and let you know.

**Comment by strib** [comment] 2017-12-06 19:27
We can reproduce the issue and see how to fix it. We've filed an internal issue to fix and hope to get to it soon.  Thanks for the report!

**Comment by jzila** [comment] 2017-12-14 00:43
All right, fix merged, it should be in the next nightly build.

**Closed by jzila** 2017-12-14 00:43 UTC
Labels: acked
